<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Username or email address</name>
   <tag></tag>
   <elementGuidId>a22a2349-24c5-4874-a33b-a18aafd47b94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.woocommerce-form-row.woocommerce-form-row--wide.form-row.form-row-wide > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='customer_login']/div/form/p/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>722308ae-b482-46a3-b595-55ced6b0cd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>e79b8b81-702c-4db3-aa81-55a7d9cb82d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username or email address *</value>
      <webElementGuid>8d29fc7d-8ed6-415a-876c-18ff6c18bbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login&quot;)/div[@class=&quot;u-column1 col-1&quot;]/form[@class=&quot;woocommerce-form woocommerce-form-login login&quot;]/p[@class=&quot;woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide&quot;]/label[1]</value>
      <webElementGuid>98067cc1-4115-44a1-8342-55ab2c43a566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div/form/p/label</value>
      <webElementGuid>3db83362-ae41-41cd-9340-f805b317e41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::label[1]</value>
      <webElementGuid>ad61321f-2eba-4ca3-b6f3-a361a45e627a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[3]/following::label[1]</value>
      <webElementGuid>3ba61711-f861-4ba2-896c-938213854155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/label</value>
      <webElementGuid>57627bad-7684-45bf-b00b-5e54ef2a823e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Username or email address *' or . = 'Username or email address *')]</value>
      <webElementGuid>548e3742-e429-4c71-a50d-b8bccc5356bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
