<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose an optionDark Blue</name>
   <tag></tag>
   <elementGuidId>4309e3ad-d394-4734-a548-c15b1ec55339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pa_color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_color']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>322e6c72-5da5-4113-b731-81743904f2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_color</value>
      <webElementGuid>38f1844e-78f4-47e3-b378-68fef732468b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_color</value>
      <webElementGuid>7997c09b-0f94-4358-80fe-e34788590a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_color</value>
      <webElementGuid>2f0acbb1-3fb4-4e0b-85b4-6fa807281b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>b0c1c5f4-9191-407f-a563-3f2e1610126e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionDark Blue</value>
      <webElementGuid>15c6c4ae-e83f-44c5-b274-d995c9886fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_color&quot;)</value>
      <webElementGuid>5e0b3979-fe6c-467a-aafa-0b33b85b38e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_color']</value>
      <webElementGuid>ccdf34c2-39d4-47d0-a040-57ee4610398a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1388']/div/div[2]/form/table/tbody/tr/td/select</value>
      <webElementGuid>ff4da163-6a5e-40a6-b1ff-bc4e9eab7ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[1]</value>
      <webElementGuid>74c86f35-e0e0-40f5-b25c-bc76e1106b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='product number'])[1]/following::select[1]</value>
      <webElementGuid>722bf371-0e58-4aec-bc6e-72149c2b1988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/preceding::select[1]</value>
      <webElementGuid>cd3ffb42-d81f-4f03-babd-b40ee06dafbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY'])[1]/preceding::select[2]</value>
      <webElementGuid>54609688-45bc-48a6-b99e-3ddd8bd82065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b0e9a895-b3ea-4935-841a-1c38882b7768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_color' and @name = 'attribute_pa_color' and (text() = 'Choose an optionDark Blue' or . = 'Choose an optionDark Blue')]</value>
      <webElementGuid>f9d31159-4456-4c96-bdb6-ddd1419ed4d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
