<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_billing_company</name>
   <tag></tag>
   <elementGuidId>16cf6ab7-9dba-4707-b100-dd440c7bb994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b38115e-c40d-48a4-bc1c-dca1617662b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a8c5b2d-4890-452b-a77a-bb94c8a37790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>1afbcd83-7b4c-4c53-9ffc-394f61cd50ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>3880152a-bf4c-4c1a-9bdd-7178248a9301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>8de1b947-dbb2-4455-8f33-69aee15556fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>4624c116-8ae5-4862-80e6-677dad3acd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_company&quot;)</value>
      <webElementGuid>1f8969ed-4f07-489a-bb3b-ca816549b1f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_company']</value>
      <webElementGuid>2d68ec50-d169-4f0d-930f-c7c67ed4a82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_company_field']/span/input</value>
      <webElementGuid>cafdf325-2183-410f-ab11-ae188336300d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/span/input</value>
      <webElementGuid>b57d705b-9d87-4fec-a06c-329c29695ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_company' and @id = 'billing_company']</value>
      <webElementGuid>4b049ce8-4b33-454a-99f4-982599b17e4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
