<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_privacy policy_terms</name>
   <tag></tag>
   <elementGuidId>e810fb04-4207-4fa1-b598-5270f7d809c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='terms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a478c5d-4bba-402e-bcb2-3fe706504d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>da5ee026-9f78-4bb7-894e-a5eda3c1bad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox input-checkbox</value>
      <webElementGuid>80f55bf5-3d46-44b8-9e3e-dab3cf95b6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>78086905-9c2f-4f98-8d40-7980d03712f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>40ee8538-a8ef-49e2-898b-9830e1ea095d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms&quot;)</value>
      <webElementGuid>fd3e1806-a939-4066-8e81-4169dfb4e6fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='terms']</value>
      <webElementGuid>a8a5b534-e064-4038-95b7-eabbbb379ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/div/div/p/label/input</value>
      <webElementGuid>7a6349fd-c8f3-449c-8c64-028b244e5e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>21885433-b879-47b2-a2a8-c6582a0eb86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'terms' and @id = 'terms']</value>
      <webElementGuid>011c6fa9-31ff-48c9-855c-d4453aee5366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
